echo "--------------------------------------------------------------------------"
echo " "
echo "You are attempting to logon to Management Information Systems Association"
echo "Amazon Web Services infrastructure."
echo " "
echo "This infrastructure is provided only for authorized MISA use."
echo " "
echo "All activities on this system is subject to monitoring for authorized use."
echo " "
echo "Unauthorized use may subject you to criminal prosecution, under the statues of"
echo "the Digital Millennium Act."
echo " "
echo "--------------------------------------------------------------------------"